#!/bin/bash
language: node_js
sudo: false
node_js:
- '8'
before_install:
- bundle install
install:
- npm install
script:
  # - travis_wait 30 npm run-script build
  - travis_wait 30 ./first.sh
  - chmod 755 first.sh
  - ./first.sh