language: node_js
sudo: false
node_js:
- '8'
before_install:
- bundle install
install:
- npm install
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - chmod 755 buildAndDeploy.sh
  - travis_wait 30 sleep infinity & ./buildAndDeploy.sh
